### ISSUE TITLE
Setup issues on blank system

### ISSUE THREAD

**Issue by tomkersten** [bigdots-io/hardware-client#1]
Here is a list of issues I ran into on a stock installation of raspian
1. No `upstart`
   - **Fix:** `apt-get install upstart`
   - **Note:** I also just ran an `apt-get update && apt-get upgrade` here and rebooted for good measure.
2. Outdated node version/no `npm` on path (v0.10.26)
   - **Fix:** Install [nvm](https://github.com/creationix/nvm) and run `nvm install v4`
   - **Note:** If you are using the `./install.sh` command as the `pi` user as described on the `Setting up a new display` page, you will want/need to either install `nvm` for both the `pi` user and `root`...or just the root user, as the `sudo` command used in the installation script will load the `root` user's path and `npm` is not on it with the base installation.

**Comment by roykolak** [comment]
updated readme w/ these notes!
